import Link from 'next/link';

export function MerchantTermsCopy() {
  return <div className="space-y-6 text-sm leading-7 text-ink-2">
    <section><h2 className="text-xl text-ink">1. About these terms</h2><p>These terms apply when you create or manage a restaurant page on BiteSite. By creating a restaurant you agree to them. BiteSite is in a pilot: features may change, and we may pause or end the pilot. We will tell you about important changes through your dashboard, by email, or by WhatsApp before they take effect.</p></section>
    <section><h2 className="text-xl text-ink">2. Fees</h2><p>BiteSite is free during the pilot. If we decide to charge for any feature later, we will tell you at least 30 days before, and you can choose not to continue.</p></section>
    <section><h2 className="text-xl text-ink">3. Your restaurant information</h2><p>You are responsible for keeping the restaurant details, menu, prices, opening hours, and other information you provide accurate and up to date.</p></section>
    <section><h2 className="text-xl text-ink">4. Content you provide</h2><p>You confirm that you are authorised to represent the restaurant and have the rights and permissions needed to provide the text and photos you add. Please avoid sharing personal information or photos of people without appropriate permission.</p><p className="mt-2">You keep ownership of your content. You allow BiteSite to store, resize, display, and share it (for example on your restaurant page, in search results, in share cards, and in BiteSite posts about your restaurant) while it is on BiteSite. This permission ends when you remove the content or your restaurant is deleted.</p></section>
    <section><h2 className="text-xl text-ink">5. Review and visibility</h2><p>BiteSite may review, request changes to, hide, or suspend a listing, for example if information is wrong, misleading, or reported by visitors. Approval does not publish a listing automatically; you choose when to publish an approved restaurant.</p></section>
    <section><h2 className="text-xl text-ink">6. Information shown to visitors</h2><p>When you publish, restaurant details and the contact information you provide for the listing may be visible to visitors. Please use contact details that you are comfortable making public.</p></section>
    <section><h2 className="text-xl text-ink">7. Your privacy</h2><p>How we use personal information is explained in the <Link href="/privacy" className="text-brand underline">BiteSite Privacy Policy</Link>.</p></section>
    <section><h2 className="text-xl text-ink">8. Leaving BiteSite</h2><p>You may stop using BiteSite at any time. You can unpublish your restaurant yourself in the dashboard. To delete your restaurant or account, email <a href="mailto:bitesite.my@gmail.com" className="text-brand underline">bitesite.my@gmail.com</a> or use Feedback in your dashboard; we handle deletion requests within 30 days.</p></section>
    <section><h2 className="text-xl text-ink">9. Our responsibility</h2><p>BiteSite is provided as it is during the pilot. We work to keep it available and accurate, but we cannot promise it will always be online or free of errors, and we are not part of orders, bookings, or payments between you and your customers.</p></section>
    <section><h2 className="text-xl text-ink">10. Contact</h2><p>Questions about these terms: <a href="mailto:bitesite.my@gmail.com" className="text-brand underline">bitesite.my@gmail.com</a>. These terms are governed by the laws of Malaysia.</p></section>
  </div>;
}
